# Generated by Django 4.2.11 on 2024-05-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='blogger',
        ),
    ]
