# Generated by Django 4.2.11 on 2024-05-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Description',
            new_name='description',
        ),
    ]
